// packages/react-client/src/app/app.tsx
// Uncomment this line to use CSS modules
// import styles from './app.module.scss';

import { SgcButton, SgcIcon, SgcMenuItem } from '@swissgeol/ui-core-react';
import styles from './app.module.scss';
import { Translate } from './translate';

export function App() {
  return (
    <div className={styles.wrapper}>
      <Translate />
      <div className={styles.buttons}>
        <SgcButton color="primary"> Primary</SgcButton>
        <SgcButton color="primary" isDisabled>
          {' '}
          Disabled
        </SgcButton>
        <SgcButton color="primary" isActive>
          {' '}
          Active
        </SgcButton>
        <SgcButton color="primary">
          <SgcIcon name="plus"></SgcIcon>
          Primary
        </SgcButton>
        <SgcButton color="primary" isDisabled>
          <SgcIcon name="plus"></SgcIcon>
          Disabled
        </SgcButton>
        <SgcButton color="primary" isActive>
          <SgcIcon name="plus"></SgcIcon>
          Active
        </SgcButton>
        <SgcButton color="primary">
          Primary
          <SgcIcon name="plus"></SgcIcon>
        </SgcButton>
        <SgcButton color="primary" isDisabled>
          Disabled
          <SgcIcon name="plus"></SgcIcon>
        </SgcButton>
        <SgcButton color="primary" isActive>
          Active
          <SgcIcon name="plus"></SgcIcon>
        </SgcButton>
        <SgcButton color="primary" variant="icon">
          <SgcIcon name="plus"></SgcIcon>
        </SgcButton>
        <SgcButton color="primary" variant="icon" isDisabled>
          <SgcIcon name="plus"></SgcIcon>
        </SgcButton>
        <SgcButton color="primary" variant="icon" isActive>
          <SgcIcon name="plus"></SgcIcon>
        </SgcButton>
        <SgcButton color="primary" variant="icon-round">
          <SgcIcon name="plus"></SgcIcon>
        </SgcButton>
        <SgcButton color="primary" variant="icon-round" isDisabled>
          <SgcIcon name="plus"></SgcIcon>
        </SgcButton>
        <SgcButton color="primary" variant="icon-round" isActive>
          <SgcIcon name="plus"></SgcIcon>
        </SgcButton>

        <SgcButton color="secondary"> Secondary</SgcButton>
        <SgcButton color="secondary" isDisabled>
          {' '}
          Disabled
        </SgcButton>
        <SgcButton color="secondary" isActive>
          {' '}
          Active
        </SgcButton>
        <SgcButton color="secondary">
          <SgcIcon name="plus"></SgcIcon>
          Secondary
        </SgcButton>
        <SgcButton color="secondary" isDisabled>
          <SgcIcon name="plus"></SgcIcon>
          Disabled
        </SgcButton>
        <SgcButton color="secondary" isActive>
          <SgcIcon name="plus"></SgcIcon>
          Active
        </SgcButton>
        <SgcButton color="secondary">
          Secondary
          <SgcIcon name="plus"></SgcIcon>
        </SgcButton>
        <SgcButton color="secondary" isDisabled>
          Disabled
          <SgcIcon name="plus"></SgcIcon>
        </SgcButton>
        <SgcButton color="secondary" isActive>
          Active
          <SgcIcon name="plus"></SgcIcon>
        </SgcButton>
        <SgcButton color="secondary" variant="icon">
          <SgcIcon name="plus"></SgcIcon>
        </SgcButton>
        <SgcButton color="secondary" variant="icon" isDisabled>
          <SgcIcon name="plus"></SgcIcon>
        </SgcButton>
        <SgcButton color="secondary" variant="icon" isActive>
          <SgcIcon name="plus"></SgcIcon>
        </SgcButton>
        <SgcButton color="secondary" variant="icon-round">
          <SgcIcon name="plus"></SgcIcon>
        </SgcButton>
        <SgcButton color="secondary" variant="icon-round" isDisabled>
          <SgcIcon name="plus"></SgcIcon>
        </SgcButton>
        <SgcButton color="secondary" variant="icon-round" isActive>
          <SgcIcon name="plus"></SgcIcon>
        </SgcButton>

        <SgcButton color="tertiary"> Tertiary</SgcButton>
        <SgcButton color="tertiary" isDisabled>
          {' '}
          Disabled
        </SgcButton>
        <SgcButton color="tertiary" isActive>
          {' '}
          Active
        </SgcButton>
        <SgcButton color="tertiary">
          <SgcIcon name="plus"></SgcIcon>
          Tertiary
        </SgcButton>
        <SgcButton color="tertiary" isDisabled>
          <SgcIcon name="plus"></SgcIcon>
          Disabled
        </SgcButton>
        <SgcButton color="tertiary" isActive>
          <SgcIcon name="plus"></SgcIcon>
          Active
        </SgcButton>
        <SgcButton color="tertiary">
          Tertiary
          <SgcIcon name="plus"></SgcIcon>
        </SgcButton>
        <SgcButton color="tertiary" isDisabled>
          Disabled
          <SgcIcon name="plus"></SgcIcon>
        </SgcButton>
        <SgcButton color="tertiary" isActive>
          Active
          <SgcIcon name="plus"></SgcIcon>
        </SgcButton>
        <SgcButton color="tertiary" variant="icon">
          <SgcIcon name="plus"></SgcIcon>
        </SgcButton>
        <SgcButton color="tertiary" variant="icon" isDisabled>
          <SgcIcon name="plus"></SgcIcon>
        </SgcButton>
        <SgcButton color="tertiary" variant="icon" isActive>
          <SgcIcon name="plus"></SgcIcon>
        </SgcButton>
        <SgcButton color="tertiary" variant="icon-round">
          <SgcIcon name="plus"></SgcIcon>
        </SgcButton>
        <SgcButton color="tertiary" variant="icon-round" isDisabled>
          <SgcIcon name="plus"></SgcIcon>
        </SgcButton>
        <SgcButton color="tertiary" variant="icon-round" isActive>
          <SgcIcon name="plus"></SgcIcon>
        </SgcButton>
      </div>
      <div className={styles.menu}>
        <SgcMenuItem
          isActive
          onItemClick={(e) => console.log('React - Menu item clicked:', e)}
        >
          Active item with content Active item with content
        </SgcMenuItem>
        <SgcMenuItem isActive isEmpty>
          Active item without content
        </SgcMenuItem>
        <SgcMenuItem isReviewed="partial">Item with content</SgcMenuItem>
        <SgcMenuItem isEmpty isReviewed="partial">
          Item without content
        </SgcMenuItem>
        <SgcMenuItem isChild>Child item with content</SgcMenuItem>
        <SgcMenuItem isActive isChild isReviewed>
          Active child item without content
        </SgcMenuItem>
      </div>
    </div>
  );
}

export default App;

// packages/angular-client/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrl: './app.component.css',
  standalone: false,
})
export class AppComponent {
  onItemClick(event: Event) {
    console.log('Angular - Menu item clicked:', event);
  }
}

<div>
  Translation:
  <sgc-translate ns="general">cancel</sgc-translate>
  ({{ counter }})
</div>

<div
  style="
    display: grid;
    grid-template-columns: repeat(15, auto);
    gap: 1rem;
    justify-items: start;
  "
>
  <sgc-button color="primary"> Primary</sgc-button>
  <sgc-button color="primary" isDisabled> Disabled</sgc-button>
  <sgc-button color="primary" isActive> Active</sgc-button>
  <sgc-button color="primary">
    <sgc-icon name="plus"></sgc-icon>
    Primary
  </sgc-button>
  <sgc-button color="primary" isDisabled>
    <sgc-icon name="plus"></sgc-icon>
    Disabled
  </sgc-button>
  <sgc-button color="primary" isActive>
    <sgc-icon name="plus"></sgc-icon>
    Active
  </sgc-button>
  <sgc-button color="primary">
    Primary
    <sgc-icon name="plus"></sgc-icon>
  </sgc-button>
  <sgc-button color="primary" isDisabled>
    Disabled
    <sgc-icon name="plus"></sgc-icon>
  </sgc-button>
  <sgc-button color="primary" isActive>
    Active
    <sgc-icon name="plus"></sgc-icon>
  </sgc-button>
  <sgc-button color="primary" variant="icon">
    <sgc-icon name="plus"></sgc-icon>
  </sgc-button>
  <sgc-button color="primary" variant="icon" isDisabled>
    <sgc-icon name="plus"></sgc-icon>
  </sgc-button>
  <sgc-button color="primary" variant="icon" isActive>
    <sgc-icon name="plus"></sgc-icon>
  </sgc-button>
  <sgc-button color="primary" variant="icon-round">
    <sgc-icon name="plus"></sgc-icon>
  </sgc-button>
  <sgc-button color="primary" variant="icon-round" isDisabled>
    <sgc-icon name="plus"></sgc-icon>
  </sgc-button>
  <sgc-button color="primary" variant="icon-round" isActive>
    <sgc-icon name="plus"></sgc-icon>
  </sgc-button>

  <sgc-button color="secondary"> Secondary</sgc-button>
  <sgc-button color="secondary" isDisabled> Disabled</sgc-button>
  <sgc-button color="secondary" isActive> Active</sgc-button>
  <sgc-button color="secondary">
    <sgc-icon name="plus"></sgc-icon>
    Secondary
  </sgc-button>
  <sgc-button color="secondary" isDisabled>
    <sgc-icon name="plus"></sgc-icon>
    Disabled
  </sgc-button>
  <sgc-button color="secondary" isActive>
    <sgc-icon name="plus"></sgc-icon>
    Active
  </sgc-button>
  <sgc-button color="secondary">
    Secondary
    <sgc-icon name="plus"></sgc-icon>
  </sgc-button>
  <sgc-button color="secondary" isDisabled>
    Disabled
    <sgc-icon name="plus"></sgc-icon>
  </sgc-button>
  <sgc-button color="secondary" isActive>
    Active
    <sgc-icon name="plus"></sgc-icon>
  </sgc-button>
  <sgc-button color="secondary" variant="icon">
    <sgc-icon name="plus"></sgc-icon>
  </sgc-button>
  <sgc-button color="secondary" variant="icon" isDisabled>
    <sgc-icon name="plus"></sgc-icon>
  </sgc-button>
  <sgc-button color="secondary" variant="icon" isActive>
    <sgc-icon name="plus"></sgc-icon>
  </sgc-button>
  <sgc-button color="secondary" variant="icon-round">
    <sgc-icon name="plus"></sgc-icon>
  </sgc-button>
  <sgc-button color="secondary" variant="icon-round" isDisabled>
    <sgc-icon name="plus"></sgc-icon>
  </sgc-button>
  <sgc-button color="secondary" variant="icon-round" isActive>
    <sgc-icon name="plus"></sgc-icon>
  </sgc-button>

  <sgc-button color="tertiary"> Tertiary</sgc-button>
  <sgc-button color="tertiary" isDisabled> Disabled</sgc-button>
  <sgc-button color="tertiary" isActive> Active</sgc-button>
  <sgc-button color="tertiary">
    <sgc-icon name="plus"></sgc-icon>
    Tertiary
  </sgc-button>
  <sgc-button color="tertiary" isDisabled>
    <sgc-icon name="plus"></sgc-icon>
    Disabled
  </sgc-button>
  <sgc-button color="tertiary" isActive>
    <sgc-icon name="plus"></sgc-icon>
    Active
  </sgc-button>
  <sgc-button color="tertiary">
    Tertiary
    <sgc-icon name="plus"></sgc-icon>
  </sgc-button>
  <sgc-button color="tertiary" isDisabled>
    Disabled
    <sgc-icon name="plus"></sgc-icon>
  </sgc-button>
  <sgc-button color="tertiary" isActive>
    Active
    <sgc-icon name="plus"></sgc-icon>
  </sgc-button>
  <sgc-button color="tertiary" variant="icon">
    <sgc-icon name="plus"></sgc-icon>
  </sgc-button>
  <sgc-button color="tertiary" variant="icon" isDisabled>
    <sgc-icon name="plus"></sgc-icon>
  </sgc-button>
  <sgc-button color="tertiary" variant="icon" isActive>
    <sgc-icon name="plus"></sgc-icon>
  </sgc-button>
  <sgc-button color="tertiary" variant="icon-round">
    <sgc-icon name="plus"></sgc-icon>
  </sgc-button>
  <sgc-button color="tertiary" variant="icon-round" isDisabled>
    <sgc-icon name="plus"></sgc-icon>
  </sgc-button>
  <sgc-button color="tertiary" variant="icon-round" isActive>
    <sgc-icon name="plus"></sgc-icon>
  </sgc-button>
</div>
<div style="display: flex; flex-direction: column">
  <sgc-menu-item active (itemClick)="onItemClick($event)">
    Active item with content
  </sgc-menu-item>
  <sgc-menu-item active empty> Active item without content </sgc-menu-item>
  <sgc-menu-item reviewed="partial"> Item with content </sgc-menu-item>
  <sgc-menu-item empty reviewed="partial"> Item without content </sgc-menu-item>
  <sgc-menu-item child> Child item with content </sgc-menu-item>
  <sgc-menu-item active child reviewed>
    Active child item without content
  </sgc-menu-item>
</div>
